version: '3.8'
services:
  mysql:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=ecommerce
      - MYSQL_ROOT_PASSWORD=soso1234
      - MYSQL_PASSWORD=soso8591
      - MYSQL_USER=soso
    ports:
      - '9306:3306'
    volumes:
      - mysql:/var/lib/mysql
volumes:
  mysql:
    driver: local