spring:
  application:
    name: notification-service
  sendgrid:
    api-key: ${SENDGRID_API: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}

server:
  port: 8500
eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA:localhost}:8761/eureka
from: dummyNumber

redis:
  host: ${REDIS_HOST:127.0.0.1}
